---
title: "In-class Exercise 5: Global and Local Measures of Spatial Autocorrelation"
execute: 
  warning: false
  eval: false
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
---

```{r}
pacman::p_load(sf,sfedp, tmap, tidyverse)
```

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```

```{r}
tmap_mode("plot")
tm_shape(hunan_GDPPC)+
  tm_fill("GDPPC", 
          style = "quantile",
          platte = "Blues",
          title = "GDPPC") +
  tm_layout(main.title = "Distribution of GDP per capita by county, Hunan province"
            main.title.position = "center",
            main.title.size = 1.2,
            legenf.height = 0.45,
            legend,widht = 0.35,
            frame = TRUE) +
  tm_borders(alpha = 0.5) +
  tm_compass(type = "8star", size = 2) +
  tm_scale_bar() +
  tm_grid(alpha = 0.2)
```

```{r}
wm_q <- hunan_GDPPC %>%
  mutate(nb = st_contiguinity(geometry),
         wt = st_weights(nb,
                         style = "w"),
         .before= 1)
```

```{r}
set.seed(1234)
```

```{r}
global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                  nsim = 99)
```
